### PR TITLE
Update conda recipe to build 4.204

### PR DESCRIPTION
**Pull request by FaustinCarter**
- Fixed issue with paths not being replaced correctly (#10 ). There is still a small issue here that results in several NULL characters following the path. This results in the following warning "Vtop.mk:13: warning: NUL character seen; rest of line ignored", but builds still work just fine.
- Pinned the versions of gcc and gxx to >=8 (since verilator relies on a compiler flag that was introduced in 8) and < 10, since there is some issue with how conda-forge is packaging some libraries that was resulting in v 7.5 of gcc and gxx getting installed during package install.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by FaustinCarter** [comment]
@conda-forge-admin, please rerender

**Comment by FaustinCarter** [comment]
@timsnyder If you have a computer with OSX and can figure out why that build is failing that would be super cool!

**Comment by timsnyder** [comment]
@FaustinCarter, I'll take a look at this and try to get it building again.  Thanks for looking last August.

**Comment by timsnyder** [comment]
@conda-forge-admin, please rerender

**Comment by timsnyder** [comment]
I think the landscape of compilers has changed since last August enough that the pinnings introduced here no longer work.  I'm going to punt on this in favor of bumping to the more recent 4.218 in #12.  @FaustinCarter if you have a need for 4.204 (I'm guessing not since we didn't get this resolved), just let me know and I'll get it built and uploaded for you.

**Pull request closed without merging**
