### PR TITLE
bump to 5.006

### PR DESCRIPTION
**Pull request by timkpaine**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by timkpaine** [comment]
@conda-forge-admin please rerender

**Comment by timsnyder** [comment]
@timkpaine thanks for helping!  I keep forgetting that I had a failing PR here.

Regarding the patch, it looks like https://github.com/verilator/verilator/pull/3881 removes the need for it.

I'm taking a quick look but it seems like python may have become a more strict requirement than run_constrained.

**Comment by timkpaine** [comment]
yeah I'll poke around a bit more later, it compiles and runs `verilator --version` fine, it looks like its looking for an absolute `python3` and I don't know if that link is set.
```
/bin/sh: /home/conda/feedstock_root/build_artifacts/verilator_1677788694769/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python3: No such file or directory
```

**Comment by timsnyder** [comment]
>  it looks like its looking for an absolute python3 and I don't know if that link is set.

yeah, in https://github.com/verilator/verilator/commit/bc7048e8d1152628669aea1ee78a4ba97054361a Wilson changed `verilator_includer` from being perl to python3.  That gets used for even simple verilator builds and I'm moving python from 'optional runtime requirements' to required.  Should fix it.

**Comment by timkpaine** [comment]
ah duh, didn't see the `run_constrained` my brain just converted it to `run`...

thanks!

**Pull request merged**
